version: "3"
services:
  hub:
    image: selenium/hub:3.14
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: "1gb"
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module:
    image: cmeatarun1988/selenium-docker
    depends_on:
      - firefox
      - hub
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - ./search-result:/usr/share/workspace/test-output
  book-flight-module:
    image: cmeatarun1988/selenium-docker
    depends_on:
      - chrome
      - hub
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=bookFlight-module.xml
    volumes:
      - ./book-result:/usr/share/workspace/test-output